### ISSUE TITLE
Minor Issue: randomising CS+/- trials

### ISSUE THREAD

**Issue by ananthamurthy** [ananthamurthy/eyeBlinkBehaviour#1]
During the Inter-Trial-Interval (ITI) phase, I use the following logic to define if the next trial will play a CS+ or a CS- frequency:

if rand(1)>0.5
    set frequency to CS+
else
    set frequency to CS-

NOTE: this happens in the ITI

ISSUE:
Across sessions, all trials form first to last, always have the same pattern of CS+/-. This is not a true randomization.

**Comment by dilawar** [comment]
srand(time(0));
