### ISSUE TITLE
New issues - 17/4/17

### ISSUE THREAD

**Issue by ananthamurthy** [ananthamurthy/eyeBlinkBehaviour#14]
- [x] Gnuplot window keeps popping to the top making it difficult to send commands in the terminal

- [x] Gnuplot shows autorange error intermittently. Unsure if pipeline halts or not.

- [x] Requirement of a dialog box to confirm new crop (online analysis). The window is too sensitive to accidental clicks.

- [x] Current online eye-blink detection algorithm gives false positive with pupil contraction

**Comment by dilawar** [comment]
Got them.

**Comment by dilawar** [comment]
The last commit might fix issue 4 and 1. You need to `git pull` before make run.

**Comment by dilawar** [comment]
- Simple click will not change the eye box.
