### ISSUE TITLE
session termination + aesthetics

### ISSUE THREAD

**Issue by ananthamurthy** [ananthamurthy/eyeBlinkBehaviour#15]
- [x] the session does not terminate after 100 trials. it keeps going on till manual "ctrl+c". also, stimuli are being delivered.

- [ ] Current trial num and number of trials till probe trial is very useful. Could we have this printed in gnuplot or terminal?

- [x] Sometimes the data line is not printed in "Animal Window". Is this a bug? this might be true only during ITI and post 100 trials.

**Comment by dilawar** [comment]
Arduino won't shut down after 100 trial. But now it wont send any data to python server.

**Comment by ananthamurthy** [comment]
Could we have the stimuli stop being delivered? In case I miss taking the
animal out, I don't want >100 presentations of the stimuli..
