### ISSUE TITLE
Incorporate Session Types

### ISSUE THREAD

**Issue by ananthamurthy** [ananthamurthy/eyeBlinkBehaviour#17]
To keep it simple, we need to implement the following logic
if sessionType_ind == 0
    traceTime = 0;
    postTime = 1400; // to allow for all trials of all different session types to have the same length
else if sessionType_ind == 1
    traceTime = 250;
    postTime = 1150;
else if sessionType_ind == 2
    traceTime = 350;
    postTime = 1050;
else if sessionType_ind == 3
    traceTime = 500;
    postTime = 900;
else //default
    traceTime = 250;
    postTime = 1150;

The postTime refers to the end of the air-puff (US) to the end of the trial. This can be modulated as required. The idea is the have the same trial duration, independent of the session type. Please edit variable names as required.

**Comment by dilawar** [comment]
Implemented. Not yet tested. Arduino cable seems to be loose. Test it and let me know if it is behaving as expected.

**Comment by ananthamurthy** [comment]
We only have to merge the new branch with master. I'm closing this issue for now.
