### ISSUE TITLE
camera imaging and image saving

### ISSUE THREAD

**Issue by Bhumikasingh0110** [ananthamurthy/eyeBlinkBehaviour#19]
Please work on the following issues:

- [x] The camera should start imaging  500ms before pre starts and 500ms after post ends.
- [x] Cchange the sound duration to 350ms.

These are the problems I found in the saved image.
- [x] All the files are saved under the K3 name(k3_1_1) even if the animal name and the trial type is different.
- [x] The trial 4 was the probe trial in the sound session but it should 7th trial(random between 5 and 10 trial).

**Comment by ananthamurthy** [comment]
Dear Bhumika,

1. The camera is currently saving 500 ms before the CS (Pre) and after the
US (Post). Did you mean you wanted to acquire for longer? This is a simple
edit to the code.

2. Same goes for CS duration (easily edited in the code). However, why do
you want a long tone? We've shown that a short CS is also effective.

3. That's odd. Are you sure you are passing the arguments properly? You
have to "cmake -DANIMAL_NAME  ..." before you "make run"

4. I think the first probe trial might be established before the
randomization. This does not ruin the behaviour at all.

Sincerely,
Ananth

**Comment by dilawar** [comment]
Bhumika

Do you want these changes in your repo? You can copy and paste it to your repository.

_Sent from my Motorola XT1706 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Bhumikasingh0110** [comment]
No, I want the changes in my branch only.

**Comment by dilawar** [comment]
> All the files are saved under the K3 name(k3_1_1) even if the animal name and the trial type is different.

Everytime you change `ANIMAL_NAME`, 'SESSION_NAME`, or `SESSION_TYPE`, you must recompile the whole setup.

     $ cmake -DANIMAL_NAME=k2 -DSESSION_TYPE=2 -DSESSION_NAME=5 ..
     $ make run

If this also shows the same behaviour, this is a bug.

> The trial 4 was the probe trial in the sound session but it should 7th trial(random between 5 and 10 trial).

This is odd! This is happening in `SOUND` (0)or `LIGHT` (1) trial types or in `MIXED` (2) types?

**Comment by dilawar** [comment]
To test it, you need to checkout branch `bhumika`. In your git clone

    $ git stash save   # It will save your uncommitted changes.
    $ git pull               # get changes from upstream 
    $ git checkout bhumika  # checkout branch `bhumika`.

**Comment by dilawar** [comment]
I tested probe trial issue. I dont see any problem. Closing it for now. Test the saving issue again and let me know.

**Comment by dilawar** [comment]
Ported all code to branch `bhumika`. The fork also track the branch `bhumika`. This is for the developer notes.
