### ISSUE TITLE
Merging issues

### ISSUE THREAD

**Issue by ananthamurthy** [ananthamurthy/eyeBlinkBehaviour#22]
Merging the branch variable_trace_post with master, didn't work as planned. There seems to be a hard-coded trace interval in the copy on behav1. One should be able to specify the session type to play out different experiments.

**Comment by dilawar** [comment]
Can put the commit number at which `main.ino` is in good shape?

**Comment by ananthamurthy** [comment]
I think this is it: 1012b3dc09c7f08df54e64ee046f8849ee101260

**Comment by dilawar** [comment]
Checkedout `main.ino` file from given commit. Test required.

**Comment by ananthamurthy** [comment]
This issue seems to have been fixed.
