### ISSUE TITLE
Git Sync issue

### ISSUE THREAD

**Issue by ananthamurthy** [ananthamurthy/eyeBlinkBehaviour#4]
Here is the error message I get when I try to sync my local copy:

fatal: Unable to create '/Users/ananth/Documents/Arduino/eye-Blink_Conditioning/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
 (128)

I'm currently unable to commit changes.

**Comment by dilawar** [comment]
Try this:

```
cd /to/repository/path
git submodule init
git submodule update
```

After this try to commit.

**Comment by ananthamurthy** [comment]
I then get this message:

Submodule path 'Arduino-Makefile': checked out
'0ce685b1a193fb4b68d7a7e8d4ed95bed8a697af'

What should I do next?

Regards,

Ananth
