### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dilawar** [ananthamurthy/eyeBlinkBehaviour#9]
For each trial 
- [x] Raw trace
- [x] Median 
- [ ] Area under the curve for some binning
- [x] Sort the trials before plotting

**Comment by dilawar** [comment]
![trial3 csv](https://cloud.githubusercontent.com/assets/895681/13944931/6923c98e-f02f-11e5-9495-6efcee707e65.png)

**Comment by ananthamurthy** [comment]
Dilawar, in the figure above, is the arrow marking "Puff" positioned correctly?
Also, I also think that the binsize should be small, e.g.- 10 ms or like in the figure above.

**Comment by dilawar** [comment]
No it's not. Just fixed it with other changes. 
On 22-Mar-2016 4:10 PM, Kambadur Ananthamurthy notifications@github.com wrote:Dilawar, in the figure above, is the arrow marking "Puff" positioned correctly?
Also, I also think that the binsize should be small, e.g.- 10 ms or like in the figure above.

**Comment by dilawar** [comment]
file:///home1/dilawars/Work/DATA/Behaviour/MouseK17/MouseK17_SessionType10_Session1/Trial3.csvseaborn-darkgrid.png 
![trial3 csvseaborn-darkgrid](https://cloud.githubusercontent.com/assets/895681/13951801/05e8929e-f059-11e5-81de-313011047094.png)

**Comment by dilawar** [comment]
Updated labnotes.
